config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :profiles

  resources :recipes


  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_one :user
  has_one :profile

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile
  has_many :recipes
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    before_action :authenticate_user!

  def after_sign_in_path_for(resource)
       profile_path(current_user.id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @apiPath = 'https://api.edamam.com/search?q='
    @appId = ENV['RECIPE_APP_ID']
    @apiKey = ENV['RECIPE_API_KEY']
    @recipe = params[:search] || "chicken"
    @response = HTTParty.get(@apiPath.to_s + "" + @recipe.to_s  + "" + @appId.to_s + "" + @apiKey.to_s + "&from=0" + "&to=5")
    @recipeResponse = JSON.parse(@response.body)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(params_profile)
    @profile.user_id = current_user.id
      if @profile.save
        redirect_to profile_path(@profile.id)
      else
        render 'new'
      end
  end

  def show
    @recipes = Recipe.where(params[:user_id] == current_user.id)
    if(Profile.exists?(current_user.id))
      @profile = Profile.find(params[:id])
    else redirect_to new_profile_path
    end
    # @recipe = Recipe.find(params[:user_id])
    @apiPath = 'https://api.edamam.com/search?q='
    @appId = ENV['RECIPE_APP_ID']
    @apiKey = ENV['RECIPE_API_KEY']
    @recipe_pref =  @profile.preference
    @response = HTTParty.get(@apiPath.to_s + "" + @recipe_pref.to_s  + ""+ @appId.to_s + "" + @apiKey.to_s + "&from=0" + "&to=5")
    @recipeResponse = JSON.parse(@response.body)

  end


  private

  def params_profile
    params.require(:profile).permit(:name, :preference, {:user_id => [current_user.id]})
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @apiPath = 'https://api.edamam.com/search?q='
    @appId = ENV['RECIPE_APP_ID']
    @apiKey = ENV['RECIPE_API_KEY']

    @recipe = params[:search]
    @response = HTTParty.get(@apiPath.to_s + "" + @recipe.to_s  + ""+ @appId.to_s + "" + @apiKey.to_s + "&from=0" + "&to=5")
    @recipeResponse = JSON.parse(@response.body)
  end
  def new
    @recipe = Recipe.new
  end
  def create
    @recipe = Recipe.create(recipe_params)
    @recipe.user_id = current_user.id

    if @recipe.save
      redirect_to profile_path(current_user.id)
    else
      render 'new'
    end
  end
  def show
    @recipe = Recipe.find(params[:id])

  end
  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
  @recipe = Recipe.find(params[:id])
  @update = @recipe.update(recipe_params)
  redirect_to profile_path(current_user)
  end
  
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to profile_path(current_user)
  end
  private
    def recipe_params
      params.require(:recipe).permit(:title, :ingredients, {:user_id =>[current_user.id]})
    end
end

app/controllers/regirstrations_controller.rb
class RegistrationsController < ApplicationController

  def after_inactive_sign_up_path_for(resource)
       new_profile_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/index.html.erb
<%= form_tag({:controller => 'home', :action => 'index'}, method: 'get') do %>
  <label for="search"></label>
  <center><%= text_field_tag :search, nil, :placeholder => "What Do You Wanna Make?" %></center>
    <center><%= submit_tag "Let's Get Cooking", :name => nil, :id => "submitHome" %></center>
<% end %>


<span id="poo">
  <% @recipeResponse["hits"].each do |response| %>
  <div class="flex-item">
    <div class="">
      <%= response["recipe"]["label"] %>
      <% @image = response["recipe"]["image"] %>
    </div>
    <div class="">
      <%= link_to image_tag(@image), {:controller => "recipes", :action => "index", :search => response["recipe"]["label"]} %>
      </div>
  </div>
  <% end %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pocketchef(Auf Deutsch)</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Shrikhand" rel="stylesheet">
    <center><strong><header>PocketChef</header></strong></center>
    <center><strong><h1>Auf Deutsch</h1></strong></center>
  </head>

  <body>
    <nav id="navBar">
      <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        <p id="userLogIn">Welcome Chef <strong><%= current_user.email %></strong></p>
        <%= link_to 'Home', root_path, :class => 'user-link' %>
        <%= link_to 'Profile', profile_path(current_user), :class => 'user-link' %>
        <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, :class => 'signoutLink'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </nav>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <%end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
<%= form_tag({:controller => 'home', :action => 'index'}, method: 'get') do %>
  <label for="search"></label>
  <center><%= text_field_tag :search, nil, :placeholder => "What Do You Wanna Make?" %></center>
    <center><%= submit_tag "Let's Get Cooking", :name => nil, :id => "submitHome" %></center>
<% end %>


<div class="flex-container">
  <% @recipeResponse["hits"].each do |response| %>
  <div class="flex-item">
    <div class="">
      <%= response["recipe"]["label"] %>
      <% @image = response["recipe"]["image"] %>
    </div>
    <div class="">
      <%= link_to image_tag(@image), {:controller => "recipes", :action => "index", :search => response["recipe"]["label"]} %>
      </div>
  </div>
  <% end %>
</div>

app/views/profiles/new.html.erb
<%= form_for :profile, url: profiles_path do |post| %>
  <p class="form-style">
    <span class="" style="display: block;">
      Username
    </span>
    <%= post.text_field :name, :placeholder => "Username"%>
  </p>
  <p class="form-style">
    <span class="" style="display: block;">
      Preference
    </span>
    <%= post.text_field :preference, :placeholder => "Preference"%>
  </p>
  <p class="actions">
    <%= post.submit "Submit", :class => 'form-submit-button'%>
  </p>
<% end %>

app/views/profiles/show.html.erb
<p>
  <%= link_to 'Edit Account', edit_user_registration_path, :id => "editAccount" %>
</p>

<p id="profileSearch">
  <%= form_tag({:controller => 'recipes', :action => 'index'}, method: 'get') do %>
    <label for="search"></label>
    <%= text_field_tag :search, nil, value: @profile.preference, :id => "profileSearchField"%>
    <%= submit_tag "Let's Get Cooking", :name => nil, :id => "profileSubmit" %>
  <% end %>

<div class="profilePreference">
  <% @recipeResponse["hits"].each do |response| %>
    <span id="imageResponseProfile">
      <p id="profileTitle">
        <%= response["recipe"]["label"] %>
      </p>
      <p id="imageSize">
        <% @image = response["recipe"]["image"] %>
        <%= link_to image_tag(@image), {:controller => "recipes", :action => "index", :search => response["recipe"]["label"]} %>
      </p>
    </span>
<%end%>
</div>

<div class="grow">
  <h3>My Lists</h3>
  <ol>
    <%if @recipes != nil%>
    <% @recipes.each do |recipe| %>
      <li>
        <%= link_to "#{recipe.title}", recipe_path(recipe) %>
      </li>
      <%end%>
    <% else %>
    <%= "Nothing added" %>
    <% end %>
  </ol>
</div>

<div id="listContainer">
</div>

app/views/recipes/edit.html.erb
<% @list = @recipe.ingredients %>

<div class="edit_form">
  <li>
  <%= form_for(@recipe, :class => "form") do |f| %>
    <p id="TitleRecipeEdit">
      <%= f.text_field :title %>
    </p>
    <p >
      <%= f.text_area :ingredients, :value => @list.to_s.gsub(/"|\[|\]/, ' ' ), :cols => "20", :rows => "10", :id => "ingredientListEdit"%>
    </p>
    <%= f.submit "Update List", :id => "recipeSubmitEdit" %>
  <% end%>
</li>
</div>

app/views/recipes/index.html.erb
<p>
  <%= form_tag({:controller => 'recipes', :action => 'index'}, method: 'get') do %>
    <label for="search"></label>
    <%= text_field_tag :search, nil, :placeholder => "What Do You Wanna Make?", :id => "recipeIndex" %>
    <%= submit_tag "Let's Get Cooking", :name => nil, :id => "submitHomeRecipe" %>
<% end %>

</p>

<div class="searchImages">
  <span>
    <%= form_for(:recipe, url: recipes_path, :class => "form") do |f| %>
      <% @recipeResponse["hits"].each do |response| %>
        <span id="imageResponseRecipe">
          <% @image = response["recipe"]["image"] %>
          <%= image_tag(@image) %>pin
          <% @title = response["recipe"]["label"] %>
          <% @ingredients=response["recipe"]["ingredientLines"] %>
          <% @poo =@ingredients %>
          <% @poo.each do |poo| %>
          <% poo.to_s.gsub(/"[^"]*"|'[^']*'|[^"'\s\W]+/,'')%>
          <% end %>
          <p id="TitleRecipe">
            <%= f.text_field :title, value: @title %>
          </p>
          <p >
            <%= f.text_area :ingredients, value: @poo , :id => "ingredientList" %>
          </p>
              <%= f.submit "Make List", :class => "recipeSubmit" %>
        </span>
        <%end%>
      <%end%>
    </span>
</div>

app/views/recipes/show.html.erb
<div class="recipe_list">
  <p id="recipeTitleShow">
    <%= @recipe.title%>
  </p>
  <p>
  <p id="recipe_ingredients">
    <ol>
      <!--Used a regex expression to remove the empty spaces/non characters and split by quotes  -->
    <% @list = @recipe.ingredients.scan(/"[^"]*"|'[^']*'|[^"'\s\W]+/) %>
    <% @list.each do |list| %>
    <li id="formatList">
      <!--Removed those double quotes -->
    <%=  list.to_s.gsub('"','' )%>
   </li>
    <% end %>
  </ol>
</p>
  </p>
</div>
<p id="showLinks">
  <%=link_to "Delete List", recipe_path(@recipe.id),:method => :delete, :id => "editList"%>
</p>
<p id="editList">
  <%=link_to "Edit List", edit_recipe_path(@recipe.id)%>
</p>